### PR TITLE
add Grid-building capabilities

### PR DESCRIPTION
**Pull request by tg44**
**The problem:**
If you want to create an excel report, and it has multiple smaller tables next and below each other, you can't compose them with the current state of the code-base. You need to create a sheet from top to bottom.

**The solution:**
Make smaller composable things (I called them Grids), whose can be arranged without explicitly knowing the absolute positions inside a sheet.

I think the examples are pretty straightforward what and how I made. I'm open to other ideas, naming, etc.

In the future, it would be nice if we could style a whole grid as is. (Like creating a header grid, giving it a background, creating a "data" grid with inner thin borders, compose them and add a new medium border for the whole.) But for the first step, I think the merging and the functions are two "killer" idea alongside the composability.

### CODE REVIEW

**Comment by tg44** [comment]
There are some minor indexing problems in the code due to the cleaning and migration, I will fix them a bit later.

**Comment by norbert-radyk** [comment]
@tg44 firstly please accept my apologies that I have taken so long to respond. Unfortunately it can happen in the holiday season that one might not have access to the computer for the extended period of time. 

As for the change itself, I would like to understand and digest the merits for it a bit more. The general idea for SPOIWO is to be a scala-friendly wrapper to Apache POI and spreadsheets generation. If you look at the current code it's fairly simple translation layer and even the names between spoiwo and POI match in 99%. 

The concept of grids, while without doubt useful, doesn't have a representation in POI or Excel (at least in the same form as implemented in the pull request) and therefore would break this simplicity of 1-1 mapping. Also not sure how would it work should we wish to start the support of SXSSF (the streaming API), which is strategically where I see the development of SPOIWO going soon. 

For me grids seems more like a natural extension library (i.e. spoiwo-grids) having it's own release cycle and repository. What do you think about this idea? I would be more than happy to add the link to your library in the Spoiwo documentation, so that more people can benefit from that feature.

**Comment by tg44** [comment]
Sorry, but this part of the year is busy for me too :D

For the 1-1 mapping, you are right, this is more like a "usability" addition. But in general, I would be interested in the general use-case of the Apache POI or this lib. 

For me, these libs are needed bcs the client needs a colorful good-looking spreadsheet. If they need only the data I use csv, and they know how to feed it to their own excel/other systems. So for me, when I start to use an excel lib the main concerns are to give me an interface so I can print data and functions and use borders between the cells, and merge cells, and give them backgrounds.
And if you want to use the Apache POI objects for excel-report generation, you will have a bad time with it. (Bcs the row-cell hierarchy is really unusual for a "grid based" application, where you want to print small tables to different positions.)
Given of these reasons, I have no idea why anybody would ever want to use some streaming functionality with excel :D If I want to stream data I would use csv (for example from the alpakka lib). (But probably I'm wrong...)


I think this is rather small for a separate lib/repo/release cycle. What do you think about the akka/alpakka style multi-module setup?



Btw the main reason I needed this code is some report which remotely looks like this:
http://www.exceluser.com/blogdata/images/post_000_302/page1.gif
If you want to create something like that and thinking with "blocks", this has two types of "tables" from four probably separated data-sources. If you write the 3 middle table renderer to one function (so you keep the original row-col based logic), how much work would be to remove the middle one, or get the third one out to a separate sheet? If you keep them as 3 separated "block" whose can be composed from left to right how much would be the same request? And these have fixed cols, but if you have dynamic row and col counts these "rendering" problems are producing a really big mess of code, bcs these apis created to easily use the underlying file format, and not to help the programmer to easily describe the solutions they need. (Just for an example, I didn't find a "merge cell" api locally, so if I want to merge cells in a function which returns rows, I need to return the merged areas too.)

**Comment by norbert-radyk** [comment]
Firstly having look at the example, I am impressed that people attempt such a complex representations/reporting in excel. 

Having said that, obviously if there is a need there needs to be a solution, I think your idea of having akka/alpakka style multi-module setup with this feature is a splendid one. I will investigate how to best set it up with spoiwo (any suggestions welcome) and hopefully in the next couple of days we can get it integrated in the nice, non-intrusive way.

**Comment by tg44** [comment]
> I am impressed that people attempt such a complex representations/reporting in excel.

I would rather use the word "sad" instead of the impressed when the client wants this :D 

I reorganized the project structure (basicly file moves and build.sbt hackery + I fixed the grid example a bit, and tested, it creates the output it should). It's just an example, if you have other ideas, names I'm happy to modify them ;)

The only thing that I'm not familiar with is the maven part. I have no idea how do you publish a new version, and bcs of that, I have no idea if the multi-module setup will be ok in this state or not. (But I'm sure this is the first step on the road.)

**Comment by norbert-radyk** [comment]
Thank you for the work on transforming spoiwo structure into the multi-module one. I have merged your changes yesteday and subsequently did a few minor library upgrades and tweaks for publishing. and published the version 1.5.0 to Nexus (I expect this to propagate to Maven Central in the next 24h).

So you should be able to download it soon as: 

<dependency>
  <groupId>com.norbitltd</groupId>
  <artifactId>spoiwo-grids_2.12</artifactId>
  <version>1.5.0</version>
</dependency>

**Comment by tg44** [comment]
Thanks for letting my module into the repo ;)

**Pull request merged**
